on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check action step
        id: checkstep
        uses: tokghwt/my-js-action@v0.1.0
        with:
          pattern: '^[feat|fix|release|chore]: #[0-9]+: '
